In [ ]:
import kagglehub
import shutil
from pathlib import Path

# Download dataset từ Kaggle
path = kagglehub.dataset_download("chelseapower/nowplayingrs")

print("Dataset downloaded to:", path)

# Thư mục muốn lưu ở ổ D
destination = Path(r"D:\KaggleDatasets\nowplayingrs")


if destination.exists():
    shutil.rmtree(destination)

# Copy dataset sang ổ D
shutil.copytree(path, destination)

print("Dataset copied to:", destination)

c:\Users\Acer\miniconda3\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\Acer\.cache\kagglehub\datasets\chelseapower\nowplayingrs\2.archive...

100%|██████████| 1.23G/1.23G [02:10<00:00, 10.1MB/s]

Extracting files...

Dataset downloaded to: C:\Users\Acer\.cache\kagglehub\datasets\chelseapower\nowplayingrs\versions\2
Dataset copied to: D:\KaggleDatasets\nowplayingrs

In [ ]:
import os

search_root = r"D:\\"

for root, dirs, files in os.walk(search_root):
    if "nowplaying" in root.lower():
        print(root)

D:\\KaggleDatasets\nowplayingrs

In [6]:
import os
import pandas as pd

path = r"D:\KaggleDatasets\nowplayingrs"

csv_files = []

for root, dirs, files in os.walk(path):
    for file in files:
        if file.lower().endswith(".csv"):
            csv_files.append(os.path.join(root, file))

print("CSV files found:")
for i, file in enumerate(csv_files):
    print(i, file)

CSV files found:
0 D:\KaggleDatasets\nowplayingrs\context_content_features.csv
1 D:\KaggleDatasets\nowplayingrs\sentiment_values.csv
2 D:\KaggleDatasets\nowplayingrs\user_track_hashtag_timestamp.csv

In [10]:
import pandas as pd

file_path = r"D:\KaggleDatasets\nowplayingrs\context_content_features.csv"

df = pd.read_csv(
    file_path,
    nrows=10000,
    on_bad_lines="skip"
)

print(df.shape)
df.head()

(10000, 22)

,coordinates,instrumentalness,liveness,speechiness,danceability,valence,loudness,tempo,acousticness,energy,...,artist_id,place,geo,tweet_lang,track_id,created_at,lang,time_zone,user_id,id
0,NaN,0.004790,0.1800,0.0294,0.634,0.342,-8.345,125.044,0.00035,0.697,...,b2980c722a1ace7a30303718ce5491d8,NaN,NaN,en,cd52b3e5b51da29e5893dba82a418a4b,2014-01-01 05:54:21,en,Central Time (US & Canada),81496937,418243774842929150
1,NaN,0.017700,0.0638,0.0624,0.769,0.752,-8.252,95.862,0.26700,0.826,...,5cddcd0e314e2f2223ab21937d2c8778,NaN,NaN,en,da3110a77b724072b08f231c9d6f7534,2014-01-01 05:54:22,en,NaN,2205686924,418243779137896450
2,NaN,0.000000,0.0860,0.0436,0.675,0.775,-4.432,97.030,0.21700,0.885,...,e41273f43af504714d85465294f1f369,NaN,NaN,en,ba84d88c10fb0e42d4754a27ead10546,2014-01-01 05:54:22,es,Mountain Time (US & Canada),132588395,418243779951198200
3,NaN,0.000000,0.1430,0.0292,0.324,0.333,-5.647,74.101,0.23900,0.574,...,557ce373bd29743eb00a3723ab19ebe8,NaN,NaN,en,33f95122281f76e7134f9cbea3be980f,2014-01-01 05:54:24,en,Eastern Time (US & Canada),97675221,418243788004687900
4,NaN,0.000183,0.3620,0.0524,0.767,0.808,-5.011,114.237,0.03640,0.739,...,77bd64b4bf77e10001fd02964985ae0f,NaN,NaN,en,b5c42e81e15cd54b9b0ee34711dedf05,2014-01-01 05:54:24,en,Central Time (US & Canada),17945688,418243789753700350

In [14]:
df['created_at']=pd.to_datetime(df['created_at'])

In [15]:
df['created_at']

0      2014-01-01 05:54:21
1      2014-01-01 05:54:22
2      2014-01-01 05:54:22
3      2014-01-01 05:54:24
4      2014-01-01 05:54:24
               ...
9995   2014-01-01 13:56:48
9996   2014-01-01 13:56:59
9997   2014-01-01 13:57:03
9998   2014-01-01 13:57:03
9999   2014-01-01 13:57:03
Name: created_at, Length: 10000, dtype: datetime64[us]

In [22]:
df.isnull().sum().sort_values(ascending=False)
df.count().sort_values(ascending=False)

created_at          10000
lang                10000
id                  10000
artist_id           10000
tempo               10000
loudness            10000
user_id             10000
tweet_lang          10000
track_id            10000
acousticness         9999
liveness             9999
instrumentalness     9999
mode                 9999
energy               9999
key                  9999
danceability         9996
speechiness          9996
valence              9995
time_zone            7182
coordinates             0
place                   0
geo                     0
dtype: int64

In [23]:
df = df.drop(columns=["place", "geo", "coordinates"])

In [24]:
df

,instrumentalness,liveness,speechiness,danceability,valence,loudness,tempo,acousticness,energy,mode,key,artist_id,tweet_lang,track_id,created_at,lang,time_zone,user_id,id
0,0.004790,0.1800,0.0294,0.634,0.342,-8.345,125.044,0.00035,0.697,1.0,6.0,b2980c722a1ace7a30303718ce5491d8,en,cd52b3e5b51da29e5893dba82a418a4b,2014-01-01 05:54:21,en,Central Time (US & Canada),81496937,418243774842929150
1,0.017700,0.0638,0.0624,0.769,0.752,-8.252,95.862,0.26700,0.826,1.0,7.0,5cddcd0e314e2f2223ab21937d2c8778,en,da3110a77b724072b08f231c9d6f7534,2014-01-01 05:54:22,en,NaN,2205686924,418243779137896450
2,0.000000,0.0860,0.0436,0.675,0.775,-4.432,97.030,0.21700,0.885,0.0,1.0,e41273f43af504714d85465294f1f369,en,ba84d88c10fb0e42d4754a27ead10546,2014-01-01 05:54:22,es,Mountain Time (US & Canada),132588395,418243779951198200
3,0.000000,0.1430,0.0292,0.324,0.333,-5.647,74.101,0.23900,0.574,1.0,7.0,557ce373bd29743eb00a3723ab19ebe8,en,33f95122281f76e7134f9cbea3be980f,2014-01-01 05:54:24,en,Eastern Time (US & Canada),97675221,418243788004687900
4,0.000183,0.3620,0.0524,0.767,0.808,-5.011,114.237,0.03640,0.739,0.0,10.0,77bd64b4bf77e10001fd02964985ae0f,en,b5c42e81e15cd54b9b0ee34711dedf05,2014-01-01 05:54:24,en,Central Time (US & Canada),17945688,418243789753700350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.038600,0.3740,0.1070,0.667,0.852,-10.812,112.541,0.03610,0.668,0.0,11.0,e2ce260a9cdfb57efd3475aa51801b5d,en,9311e49acb880911cad5b1d7f4d66edf,2014-01-01 13:56:48,en,Pacific Time (US & Canada),946275781,418365189546049540
9996,0.000000,0.1810,0.0695,0.729,0.657,-5.012,95.016,0.13100,0.860,1.0,7.0,056f6752c50543b9ca78380edd1627d3,en,1a9466ae98a6e95e201749bfccbd7436,2014-01-01 13:56:59,en,NaN,1355626086,418365235888914400
9997,0.037600,0.1520,0.0295,0.775,0.873,-3.598,131.340,0.13500,0.866,1.0,9.0,98ba6c1cd404a9ac032aa95a854e25b3,sk,27876b9f93711738e92ca03e252a373d,2014-01-01 13:57:03,en,Eastern Time (US & Canada),24526077,418365250300174340
9998,0.000003,0.0627,0.0396,0.523,0.824,-3.689,172.054,0.03130,0.808,1.0,2.0,86bb1126d3dfb2bb6dac1d3ffd2047f8,en,128cac56f1890223c5c36f0fa5f11b7c,2014-01-01 13:57:03,en,Eastern Time (US & Canada),300323651,418365251298791400
9999,0.000000,0.2390,0.0711,0.469,0.352,-3.713,137.963,0.00183,0.846,1.0,9.0,db4601a6d47792a4b73b9b9c9f02d737,en,b751ff1e64eebf5815eced83d85405c4,2014-01-01 13:57:03,en,Melbourne,164067322,418365253697536000