In [2]:
#1. Import libraries
import kagglehub
import shutil
from sklearn.preprocessing import LabelEncoder
from pathlib import Path
from scipy.sparse import csr_matrix

#2. Load dataset
path = kagglehub.dataset_download("chelseapower/nowplayingrs")

print("Dataset downloaded to:", path)


destination = Path(r"D:\KaggleDatasets\nowplayingrs")


if destination.exists():
    shutil.rmtree(destination)


shutil.copytree(path, destination)

print("Dataset copied to:", destination)

Dataset downloaded to: C:\Users\Acer\.cache\kagglehub\datasets\chelseapower\nowplayingrs\versions\2
Dataset copied to: D:\KaggleDatasets\nowplayingrs

In [3]:
import os

search_root = r"D:\\"

for root, dirs, files in os.walk(search_root):
    if "nowplaying" in root.lower():
        print(root)

D:\\KaggleDatasets\nowplayingrs

In [4]:
import os
import pandas as pd

path = r"D:\KaggleDatasets\nowplayingrs"

csv_files = []

for root, dirs, files in os.walk(path):
    for file in files:
        if file.lower().endswith(".csv"):
            csv_files.append(os.path.join(root, file))

print("CSV files found:")
for i, file in enumerate(csv_files):
    print(i, file)

CSV files found:
0 D:\KaggleDatasets\nowplayingrs\context_content_features.csv
1 D:\KaggleDatasets\nowplayingrs\sentiment_values.csv
2 D:\KaggleDatasets\nowplayingrs\user_track_hashtag_timestamp.csv

In [5]:
import pandas as pd
#đọc full dataset 
file_path = r"D:\KaggleDatasets\nowplayingrs\context_content_features.csv"

df = pd.read_csv(
    file_path,
    on_bad_lines="skip"
)

print(df.shape)
df.head()

C:\Users\Acer\AppData\Local\Temp\ipykernel_154796\1967077823.py:5: DtypeWarning: Columns (0: coordinates, 1: place, 2: geo) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

(11606689, 22)

,coordinates,instrumentalness,liveness,speechiness,danceability,valence,loudness,tempo,acousticness,energy,...,artist_id,place,geo,tweet_lang,track_id,created_at,lang,time_zone,user_id,id
0,NaN,0.004790,0.1800,0.0294,0.634,0.342,-8.345,125.044,0.00035,0.697,...,b2980c722a1ace7a30303718ce5491d8,NaN,NaN,en,cd52b3e5b51da29e5893dba82a418a4b,2014-01-01 05:54:21,en,Central Time (US & Canada),8.149694e+07,418243774842929150
1,NaN,0.017700,0.0638,0.0624,0.769,0.752,-8.252,95.862,0.26700,0.826,...,5cddcd0e314e2f2223ab21937d2c8778,NaN,NaN,en,da3110a77b724072b08f231c9d6f7534,2014-01-01 05:54:22,en,NaN,2.205687e+09,418243779137896450
2,NaN,0.000000,0.0860,0.0436,0.675,0.775,-4.432,97.030,0.21700,0.885,...,e41273f43af504714d85465294f1f369,NaN,NaN,en,ba84d88c10fb0e42d4754a27ead10546,2014-01-01 05:54:22,es,Mountain Time (US & Canada),1.325884e+08,418243779951198200
3,NaN,0.000000,0.1430,0.0292,0.324,0.333,-5.647,74.101,0.23900,0.574,...,557ce373bd29743eb00a3723ab19ebe8,NaN,NaN,en,33f95122281f76e7134f9cbea3be980f,2014-01-01 05:54:24,en,Eastern Time (US & Canada),9.767522e+07,418243788004687900
4,NaN,0.000183,0.3620,0.0524,0.767,0.808,-5.011,114.237,0.03640,0.739,...,77bd64b4bf77e10001fd02964985ae0f,NaN,NaN,en,b5c42e81e15cd54b9b0ee34711dedf05,2014-01-01 05:54:24,en,Central Time (US & Canada),1.794569e+07,418243789753700350

In [6]:
df['created_at']

0           2014-01-01 05:54:21
1           2014-01-01 05:54:22
2           2014-01-01 05:54:22
3           2014-01-01 05:54:24
4           2014-01-01 05:54:24
                   ...
11606684    2014-12-23 07:21:02
11606685    2014-12-23 07:21:04
11606686    2014-12-23 07:21:07
11606687    2014-12-23 07:21:08
11606688    2014-12-23 07:21:11
Name: created_at, Length: 11606689, dtype: str

In [7]:
#Xem thử có bao nhiêu hàng NULL theo cột
df.isnull().sum().sort_values(ascending=False)

coordinates         11575689
geo                 11575689
place               11570327
time_zone            3260480
user_id                36362
valence                 4787
speechiness             3887
danceability            3887
liveness                2913
instrumentalness        2801
acousticness            2786
energy                  2760
key                     2713
mode                    2713
lang                      64
artist_id                  0
tempo                      0
loudness                   0
created_at                 0
track_id                   0
tweet_lang                 0
id                         0
dtype: int64

In [8]:
df = df.drop(columns=["place", "geo", "coordinates"])

In [9]:
df

,instrumentalness,liveness,speechiness,danceability,valence,loudness,tempo,acousticness,energy,mode,key,artist_id,tweet_lang,track_id,created_at,lang,time_zone,user_id,id
0,0.004790,0.1800,0.0294,0.634,0.342,-8.345,125.044,0.000350,0.697,1.0,6.0,b2980c722a1ace7a30303718ce5491d8,en,cd52b3e5b51da29e5893dba82a418a4b,2014-01-01 05:54:21,en,Central Time (US & Canada),8.149694e+07,418243774842929150
1,0.017700,0.0638,0.0624,0.769,0.752,-8.252,95.862,0.267000,0.826,1.0,7.0,5cddcd0e314e2f2223ab21937d2c8778,en,da3110a77b724072b08f231c9d6f7534,2014-01-01 05:54:22,en,NaN,2.205687e+09,418243779137896450
2,0.000000,0.0860,0.0436,0.675,0.775,-4.432,97.030,0.217000,0.885,0.0,1.0,e41273f43af504714d85465294f1f369,en,ba84d88c10fb0e42d4754a27ead10546,2014-01-01 05:54:22,es,Mountain Time (US & Canada),1.325884e+08,418243779951198200
3,0.000000,0.1430,0.0292,0.324,0.333,-5.647,74.101,0.239000,0.574,1.0,7.0,557ce373bd29743eb00a3723ab19ebe8,en,33f95122281f76e7134f9cbea3be980f,2014-01-01 05:54:24,en,Eastern Time (US & Canada),9.767522e+07,418243788004687900
4,0.000183,0.3620,0.0524,0.767,0.808,-5.011,114.237,0.036400,0.739,0.0,10.0,77bd64b4bf77e10001fd02964985ae0f,en,b5c42e81e15cd54b9b0ee34711dedf05,2014-01-01 05:54:24,en,Central Time (US & Canada),1.794569e+07,418243789753700350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11606684,0.000000,0.1220,0.1380,0.758,0.914,-14.741,119.507,0.347000,0.477,1.0,0.0,be8e7dd0afe257f9b6b4a196b7f97e82,en,da58ba1ca758809bb86aa8e3a36d1ecc,2014-12-23 07:21:02,en,Melbourne,4.311438e+08,547275669160615940
11606685,0.000107,0.1680,0.0291,0.626,0.360,-7.006,132.349,0.664000,0.526,1.0,7.0,cbb893ee95d9d9db2f072d12e8a6ee9b,en,03498f305040835c5f76d7c5660204a2,2014-12-23 07:21:04,en,Central Time (US & Canada),2.819332e+09,547275678563831800
11606686,0.000000,0.0892,0.0378,0.375,0.340,-12.952,62.777,0.932000,0.115,0.0,0.0,4310e62dea15976a9bd476de6d3fdb1d,en,8bacefe018a221d933529dd466e7c1c0,2014-12-23 07:21:07,en,Tokyo,1.540709e+08,547275692044324860
11606687,0.000679,0.0836,0.0296,0.312,0.229,-9.146,130.795,0.131000,0.418,1.0,7.0,aa968850a9d255494612acd0552f8fcd,en,0e64c11b9a77e93f343f9c1c0cdbcf54,2014-12-23 07:21:08,en,Melbourne,9.855916e+08,547275696855212000
11606688,0.002170,0.0504,0.0299,0.377,0.277,-8.039,108.736,0.000894,0.682,1.0,7.0,cb725823157e6b10da8fa376c2e1b013,en,af5c5f220e0a872ac129f4f88b3db5f9,2014-12-23 07:21:11,en,Eastern Time (US & Canada),1.551878e+07,547275707853062140

In [10]:
#check xem tốn bao nhiêu ram
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
df.info(memory_usage="deep")

Rows: 11606689
Columns: 19
<class 'pandas.DataFrame'>
RangeIndex: 11606689 entries, 0 to 11606688
Data columns (total 19 columns):
 #   Column            Dtype
---  ------            -----
 0   instrumentalness  float64
 1   liveness          float64
 2   speechiness       float64
 3   danceability      float64
 4   valence           float64
 5   loudness          float64
 6   tempo             float64
 7   acousticness      float64
 8   energy            float64
 9   mode              float64
 10  key               float64
 11  artist_id         str
 12  tweet_lang        str
 13  track_id          str
 14  created_at        str
 15  lang              str
 16  time_zone         str
 17  user_id           float64
 18  id                int64
dtypes: float64(12), int64(1), str(6)
memory usage: 5.3 GB

In [11]:
df = df.dropna(subset=["user_id", "track_id"])

In [12]:
dup=df.duplicated().sum()

In [13]:
interaction=(
    
    df.groupby(["user_id","track_id"]).size().reset_index(name="Play count")
)

In [14]:
interaction.sort_values("Play count",ascending=False)

              user_id                          track_id  Play count
70099    1.551878e+07  7188f922ba73eb2509c02d15ec62ff0e       10326
1889085  5.344929e+08  e24deb4963769d25e2c03ad9bf58a028        9287
1883222  5.314516e+08  e24deb4963769d25e2c03ad9bf58a028        4440
2388020  1.371597e+09  01e010349c1a3415c9b0b65f04ad2fed        2333
70006    1.551878e+07  3eed040f245b4c06196e77dd57d6aefd        2258
...               ...                               ...         ...
3030552  2.933521e+09  a048a86d8cab3c28065516e88e762176           1
3030567  2.935057e+09  73e2fa180ede6af69e1f89734009cf0a           1
3030566  2.935057e+09  70e3cc1c1206d793ebb55e9924caebce           1
3030565  2.935057e+09  6803b6d444cb02e4a3623a5cc30357a9           1
4        3.713000e+03  0c8aaf4dcfdbeb4b616d987615c296d3           1

[3030580 rows x 3 columns]

In [15]:
user_songs_count=interaction.groupby("user_id")["track_id"].nunique()

In [16]:
valid_user=user_songs_count[user_songs_count>=5].index

In [17]:
interaction_filtered=interaction[interaction["user_id"].isin(valid_user)].copy()

In [18]:
interaction_filtered.sort_values("Play count",ascending=False)

              user_id                          track_id  Play count
70099    1.551878e+07  7188f922ba73eb2509c02d15ec62ff0e       10326
1889085  5.344929e+08  e24deb4963769d25e2c03ad9bf58a028        9287
1883222  5.314516e+08  e24deb4963769d25e2c03ad9bf58a028        4440
70006    1.551878e+07  3eed040f245b4c06196e77dd57d6aefd        2258
69960    1.551878e+07  2309b1481773d5bdba0a0772f149cebd        2242
...               ...                               ...         ...
727496   9.744575e+07  05d5516accafb585772394ce4fd18471           1
17       3.713000e+03  b23d6c86e5da9f9eb06ae0bd95ee383f           1
16       3.713000e+03  aa57f08c6a5f091dbe0389d16680c049           1
15       3.713000e+03  a084d3de65e93f7333595c8ab9de3dcf           1
3030516  2.929583e+09  6072ca48799542f04dd60804b2440e77           1

[2917315 rows x 3 columns]

In [19]:
Song_play_count=interaction_filtered.groupby("track_id")["Play count"].sum()

Valid_song=Song_play_count[Song_play_count>=5].index

Valid_song

Index(['00003213fb3d4959f42e9157b0eda0a5', '00008919c4c0537f3f5808b06c156bc9',
       '0000e47c1207e2c637a44753a713456f', '00019c62663e3a06ea4b3b3a74a983ef',
       '0001a423baf29add84af6ec58aeb5b90', '0001dc79946a42fbc837c044be0bdbbc',
       '00021ef2826cb82f4d112069a340230e', '000248c97c5991b9900360aca97d9879',
       '00027df4d0bd64108624757fe4cbfe76', '000359abe73f500143335921d078a7b0',
       ...
       'fffd0d291f4addb6c4640a0f50d22f3f', 'fffd0e6aa371d5d9f325092b4b176a5b',
       'fffd293d9450783348d5f9d169ed8abe', 'fffd98dceef2bc37fe905f026025b561',
       'fffdc3fe920537e196890ad1785b717b', 'fffdf00857154771de0d8479d8341e1e',
       'fffe595c15857cad1afb20eea9a8becb', 'fffe80afaa2dc335b5de8ee8862ab47a',
       'fffee57c8c12d3cb9034befffa541313', 'fffef37bec01701ce5f548fbdb26ad8b'],
      dtype='str', name='track_id', length=173980)

In [20]:
interaction_after_filtered=interaction_filtered[interaction_filtered["track_id"].isin(Valid_song)].copy()

In [21]:
interaction_after_filtered.sort_values("Play count",ascending=False)

              user_id                          track_id  Play count
70099    1.551878e+07  7188f922ba73eb2509c02d15ec62ff0e       10326
1889085  5.344929e+08  e24deb4963769d25e2c03ad9bf58a028        9287
1883222  5.314516e+08  e24deb4963769d25e2c03ad9bf58a028        4440
70006    1.551878e+07  3eed040f245b4c06196e77dd57d6aefd        2258
69960    1.551878e+07  2309b1481773d5bdba0a0772f149cebd        2242
...               ...                               ...         ...
3030547  2.933521e+09  67f129f0ea5e9eee024ad1c4d8676944           1
3030550  2.933521e+09  804daee4f26a1653e48f0b2f30935d98           1
3030552  2.933521e+09  a048a86d8cab3c28065516e88e762176           1
3030553  2.933521e+09  ab1b870900af36658691d668682fb99e           1
3030554  2.933521e+09  e3cbdaf7559665dc3be932f2b66c2ef8           1

[2651047 rows x 3 columns]

In [22]:
interaction_after_filtered['track_id'].nunique()

173980

In [23]:
df_new=interaction_after_filtered.copy()

In [24]:

le_user = LabelEncoder()
df_new['user_id_enc'] = le_user.fit_transform(df_new['user_id'])

unique_users = sorted(df_new['user_id'].unique())
unique_tracks = sorted(df_new['track_id'].unique())

user2idx = {u: i for i, u in enumerate(unique_users)}
track2idx = {t: i for i, t in enumerate(unique_tracks)}


idx2user = {i: u for u, i in user2idx.items()}
idx2track = {i: t for t, i in track2idx.items()}

df_new['user_id_enc'] = df_new['user_id'].map(user2idx)
df_new['track_id_enc'] = df_new['track_id'].map(track2idx)

In [25]:
df_new

,user_id,track_id,Play count,user_id_enc,track_id_enc
4,3.713000e+03,0c8aaf4dcfdbeb4b616d987615c296d3,1,0,8598
5,3.713000e+03,0dc0cd2aa19403dc3fb47b4a309ffd58,1,0,9440
10,3.713000e+03,3bc965ef94fc05882119bc9667fc2948,1,0,40617
11,3.713000e+03,3d513474568a69f39f5e7b3d493d8628,1,0,41628
15,3.713000e+03,a084d3de65e93f7333595c8ab9de3dcf,1,0,109175
...,...,...,...,...,...
3030573,2.935057e+09,b0635b35ec1482d672d16bb6a0ae4a86,1,66298,120150
3030574,2.935057e+09,b45ac77d664e977bea1740d5012a2acb,1,66298,122787
3030575,2.935057e+09,bc7a5dfd0f50bf055393628d3449526c,1,66298,128287
3030576,2.935057e+09,c612e909ea4bd5ee6da54d9ef7da5e4c,1,66298,134831
3030577,2.935057e+09,dca2bf671dae863698eb31fc317a8319,1,66298,149992

In [26]:
from scipy.sparse import csr_matrix
import numpy as np


n_users = df_new['user_id_enc'].max() + 1    # 66299
n_songs = df_new['track_id_enc'].max() + 1   # 149993


sparse_matrix = csr_matrix(
    (df_new['Play count'].values,
     (df_new['user_id_enc'].values, df_new['track_id_enc'].values)),
    shape=(n_users, n_songs)
)

print(f"Shape       : {sparse_matrix.shape}")
print(f"Non-zeros   : {sparse_matrix.nnz:,}")
print(f"Sparsity    : {1 - sparse_matrix.nnz / (n_users * n_songs):.6f}")

Shape       : (66299, 173980)
Non-zeros   : 2,651,047
Sparsity    : 0.999770

In [27]:
#Kiểm tra độ sparse 
nnz = sparse_matrix.count_nonzero()

rows, cols = sparse_matrix.shape

sparsity = 1 - (nnz / (rows * cols))

print(f"Sparsity: {sparsity:.4f}")

Sparsity: 0.9998

In [28]:
#Bước 8 
from scipy.sparse.linalg import svds
from scipy.sparse import csr_matrix
import numpy as np

In [29]:
# ── 8.1  Chuẩn hoá Play count → log scale
# Play count có thể rất lệch (vài user nghe 1 bài hàng trăm lần)
# Log giúp giảm ảnh hưởng của outliers, tương tự như implicit feedback
log_matrix = sparse_matrix.copy().astype(np.float32)
log_matrix.data = np.log1p(log_matrix.data)   # log(1 + play_count)

In [30]:
# ── 8.2  Truncated SVD ─
# R ≈ U · Σ · Vt
# - U   : (n_users, K)  — user latent factors
# - Σ   : (K,)          — singular values (độ "quan trọng" mỗi chiều)
# - Vt  : (K, n_songs)  — song latent factors (transpose)
#
# k=64 → mỗi user và song được biểu diễn bằng 64 chiều ẩn
 
K = 64
 
print(f"Đang chạy Truncated SVD với K={K} chiều ẩn...")
print(f"Ma trận đầu vào: {log_matrix.shape[0]:,} users × {log_matrix.shape[1]:,} songs")
 
U, sigma, Vt = svds(log_matrix, k=K)
 
# svds trả về theo thứ tự tăng dần → đảo ngược để chiều quan trọng nhất ở đầu
U      = U[:, ::-1]          # (66299, 64)
sigma  = sigma[::-1]         # (64,)
Vt     = Vt[::-1, :]         # (64, 173980)

Đang chạy Truncated SVD với K=64 chiều ẩn...
Ma trận đầu vào: 66,299 users × 173,980 songs

In [31]:
# ── 8.3  Tạo embedding vectors
# Nhân với căn sigma để scale đúng mức — cách chuẩn trong SVD-based MF
# user_embeddings[u]  = vector 64 chiều của user u
# song_embeddings[i]  = vector 64 chiều của song i
 
sqrt_sigma = np.sqrt(sigma)                  # (64,)
 
user_embeddings = U * sqrt_sigma             # (66299, 64)
song_embeddings = (Vt.T) * sqrt_sigma        # (173980, 64)

In [32]:
# ── 8.4  Kiểm tra kết quả 
print("\n SVD hoàn tất!")
print(f"   user_embeddings : shape = {user_embeddings.shape}  | dtype = {user_embeddings.dtype}")
print(f"   song_embeddings : shape = {song_embeddings.shape}  | dtype = {song_embeddings.dtype}")
print(f"   Sigma (top 5)   : {sigma[:5].round(2)}")
 
# Phần trăm variance được giải thích bởi K chiều
explained = (sigma**2).sum() / (log_matrix.data**2).sum() * 100
print(f"   Variance giải thích được: {explained:.2f}%")

 SVD hoàn tất!
   user_embeddings : shape = (66299, 64)  | dtype = float32
   song_embeddings : shape = (173980, 64)  | dtype = float32
   Sigma (top 5)   : [409.64 260.04 257.26 240.3  212.6 ]
   Variance giải thích được: 31.22%

In [33]:
# ── 8.5  Ví dụ: lấy embedding của user/song bất kỳ 
sample_user_id  = df_new['user_id'].iloc[0]       # user đầu tiên trong df
sample_track_id = df_new['track_id'].iloc[0]      # track đầu tiên trong df
 
u_idx = user2idx[sample_user_id]
t_idx = track2idx[sample_track_id]
 
print(f"\n Ví dụ embedding:")
print(f"   User  {sample_user_id}  → index {u_idx} → vector (5 chiều đầu): {user_embeddings[u_idx, :5].round(4)}")
print(f"   Track {sample_track_id} → index {t_idx} → vector (5 chiều đầu): {song_embeddings[t_idx, :5].round(4)}")

 Ví dụ embedding:
   User  3713.0  → index 0 → vector (5 chiều đầu): [ 0.0004  0.0002 -0.0007  0.     -0.0012]
   Track 0c8aaf4dcfdbeb4b616d987615c296d3 → index 8598 → vector (5 chiều đầu): [ 0.0314  0.0154 -0.0448  0.0006 -0.0734]

In [34]:
# ── 8.6  Kiểm tra dự đoán: score user-song 
# Dự đoán "độ phù hợp" = tích vô hướng user vector · song vector
pred_score = np.dot(user_embeddings[u_idx], song_embeddings[t_idx])
print(f"\n   Predicted score (user × song dot product): {pred_score:.4f}")

   Predicted score (user × song dot product): 0.0007

In [35]:
# ── 8.7  Recommend top-N songs cho 1 user 
def recommend_songs(user_id, top_n=10):
    """
    Trả về top_n song được dự đoán là phù hợp nhất với user_id.
    Loại bỏ những bài user đã nghe.
    """
    u_idx = user2idx[user_id]
 
    # Tính score với tất cả songs: (64,) · (173980, 64).T → (173980,)
    scores = song_embeddings @ user_embeddings[u_idx]
 
    # Lấy index các bài user ĐÃ nghe để loại ra
    listened = set(sparse_matrix[u_idx].indices)
 
    # Sắp xếp giảm dần, bỏ những bài đã nghe
    ranked = np.argsort(-scores)
    rec_indices = [i for i in ranked if i not in listened][:top_n]
 
    # Map về track_id gốc
    return [idx2track[i] for i in rec_indices]

In [36]:
# Test thử
sample_recs = recommend_songs(sample_user_id, top_n=5)
print(f"\n Top-5 gợi ý cho user {sample_user_id}:")
for rank, track_id in enumerate(sample_recs, 1):
    print(f"   {rank}. {track_id}")

 Top-5 gợi ý cho user 3713.0:
   1. d5b9fd9f567579ab21d758e03edee0f6
   2. 85a2a61ff1dcd22d665eb70795930879
   3. 97491a58950ab1bfafeb1d14ff1150d7
   4. 793198054698107e20d2cb2081b5330c
   5. d70c05e0d217e85a7d9b408464c09e68

In [47]:
user_context = (
    df[['user_id', 'tweet_lang', 'lang', 'time_zone']]
    .drop_duplicates(subset='user_id')
    .set_index('user_id')
    .loc[list(user2idx.keys())]          
)

In [48]:
# Dictionary encode 3 cột
for col in ['tweet_lang', 'lang', 'time_zone']:
    unique_vals = user_context[col].dropna().unique().tolist()
    val2idx = {v: i+1 for i, v in enumerate(unique_vals)}  # 0 = unknown/NaN
    user_context[col] = user_context[col].map(val2idx).fillna(0).astype(int)

In [ ]:
#Ghép user_embedding với các user_context ở trên
context_features = user_context.values                    
user_combined = np.concatenate([user_embeddings, context_features], axis=1)

print(f"user_combined: {user_combined.shape}")

user_combined: (66299, 67)